### ISSUE TITLE
Debugging current impl of a fenced frame

### ISSUE THREAD

**Issue by piwanczak** [shivanigithub/fenced-frame#10]
While playing around the current implementation of Fenced Frames I wanted to be able to programmatically access contents of a Fenced Frame.
Usually, for such automated testing I'd use either Selenium or CDP (Chrome DevTools Protocol) commands for more obscure use cases. 
Those ways seems not to be (yet) available for the nightlies.
Selenium bindings seem to treat fenced frame differently from other iframes and won't allow "switching" into the frame.
CDP does not (to the best of my knowledge) expose a way to access the contents of a fenced frame
Yet, the DevTools through the UI allow access to the Fenced Frames contents.

A simplified test case I'd like to run looks like this:
- load test page w/ fenced frame
- run an assertion if the fenced frame exists
- run an assertion on the fenced frame's contents (ie: 

Please also have a look at the public tests that we've got published:
https://github.com/RTBHOUSE/chromium-fledge-tests/pull/20/commits/8b7094372d43a71db1f471a781fa72956aaa2558

I was wondering if you could point me to the right direction - how can I build an automated test against a Fenced Frame with the current builds at hand?

**Comment by shivanigithub** [comment]
Thanks for the question!

Can you check if it's working correctly on using the fenced frames architecture as shadow_dom. 
From the command line, you can use --enable-features=FencedFrames:implementation_type/shadow_dom or select "Enabled With ShadowDOM" from about:flags.

For the team to investigate the issue that you are seeing it would be great if you can create a bug at [crbug.com](https://crbug.com) and also mention which implementation type has the issue in the bug description. Thanks!

/cc @dtapuska

**Comment by dtapuska** [comment]
@mathiasbynens Can you comment on this? I wonder if chromedriver needs to be updated to handle fenced frames much as it did to handle OOPIFs like: https://chromium-review.googlesource.com/c/chromium/src/+/934145/

I know @a4sriniv did work for devtools frontend.

**Comment by piwanczak** [comment]
Thanks, folks! Would appreciate any and all guidance possible

I've submitted a crbug as well: https://bugs.chromium.org/p/chromium/issues/detail?id=1290330

For the record - ideally I'd want to utilise Selenium or similar automated testing, but if available I'd be also happy with CDTP commands that could realise our test scenario and run some basic assertion on the FencedFrame's contents
