### ISSUE TITLE
Fenced Frames Nesting 

### ISSUE THREAD

**Issue by piwanczak** [shivanigithub/fenced-frame#2]
Thank you for submitting this proposal, sounds really interesting!

As per your explainer - a Fenced Frame is a “top-level browsing context”. 

For some use cases it would be great to have the possibility to separate contexts not only from the top level browsing context, but also from children. 
One of such cases is [PLTD](https://github.com/jonasz/product_level_turtledove) where adequate privacy protection requires for the “ad” frame to be blind of it’s “product” children [see: section “[Creative Construction](https://github.com/jonasz/product_level_turtledove#creative-construction)”]. 

Could you please share your thoughts on nesting of Fenced Frames?

**Comment by shivanigithub** [comment]
Thanks for creating the issue!

To understand the use case, is it multiple creatives that are part of the same web bundle and are created as nested iframes within a single document?

In general, if the document hosted in a fenced frame creates nested iframes, they would be able to talk to each other like a normal page but will not be able to talk to the publisher page that embeds the fenced frame. To remove the capability of those nested frames to talk to each other or to their parent, they would need to be created as fenced frames as well.

**Comment by piwanczak** [comment]
Thank you for the response and clear answer!

Your understanding is correct. 
In our scenario a "top" fenced frame we'd call "ad template" should not learn of the contents of nested elements we call "products".
