### ISSUE TITLE
Content blocking and the initial implementation of fenced frames

### ISSUE THREAD

**Issue by felipeerias** [shivanigithub/fenced-frame#7]
Since the initial implementation of fenced frames will allow network access, my understanding is that existing functionality for blocking specific network requests (e.g. [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) in Chrome) should continue to work as it does now.

Even if the embedding page only sees the opaque `urn:uuid` value, the requests coming from within the fenced frame will use the actual URL values and will be available for content blocking.

Would it be possible to confirm this?

**Comment by shivanigithub** [comment]
That is correct. Content blockers will continue to work normally. 
This is also discussed in the design doc [here](https://docs.google.com/document/d/17rtX55WkxMcfh6ipuhP4mNULIVxUApvYt4ZYXfX2x-s/edit#heading=h.5vbbrxo3hzye)
